


import "../../src/globals.css";

import SobreNosotros from "./page";



export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function layoutNosotros({children}) {
  return (
    <html lang="en">
      <body
        className=" "
      >


         {/* Sobre Nosotros */}
         
        <SobreNosotros />
        
        {children}

      </body>
    </html>
  );
}