


import "../../src/globals.css";

import SobreNosotros from "./page";



export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function nosotrosLayout({children}) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-b from-azure to-blue-500 h-screen h-100% "
      >


         {/* Sobre Nosotros */}
         
        <SobreNosotros />
      
        {children}

      </body>
    </html>
  );
}