import "../../src/globals.css";
import RegistroHospital from "./RegistroHospital"; // Si está en la misma carpeta

// Si no estás usando las fuentes, eliminamos las importaciones relacionadas

export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function LayoutRegistro({ children }) {
  return (
    <body className="sm:m-0">
      {/* Registro Hospital */}
      <RegistroHospital />
      {children}
    </body>
  );
}
