import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "../componentes/Navbar";
import "../../src/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function RootLayout({ children }) {
  return (

     /*nota importante: en Tailwind.css los bordes se colocan dentro del className de cada etiqueta y comienzan con la palabra: border , ejemplo: border-2 border-solid border-white, 
        cuando desee eliminarlos dirijase al className donde se encuentre y los borra*/

        /*nota importante: Si nota que aparecen bordes en su pagina y sin embargo no estan creados en su className, dirijase al archivo page.css correspondiente a dicha pagina
        lo ma probable es que haya sido creado allí y cuando no los necesite, los puede borrar*/

    <html lang="en">
      <body
      //prueba del responsive design, para tamaño pequeño el background sera de color negro, para dispositivos medianos, el background sera azul
      
        className="bg:blue sm: bg-blue md:bg-blue border-2 border-solid border-white"
      >


         {/* Navbar principal */}
         
        <Navbar />
        {children}


      </body>
    </html>
  );
}