import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "../componentes/Navbar";
import "../../src/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-r from-white to-blue-700 h-screen h-100%"
      >

         {/* Navbar principal */}
         
        <Navbar />
        {children}


      </body>
    </html>
  );
}