import { Geist, Geist_Mono } from "next/font/google";


import "../../src/globals.css";
import InicioUsuario from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Geosalud",
  description: "Generated by Geosalud",
};

export default function layoutInicioUsuario({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-b from-azure to-blue-500 h-screen h-100% "
      >


         {/* Inicio Usuario */}
         
        < InicioUsuario/>
        {children}


      </body>
    </html>
  );
}